### ISSUE TITLE
Try using Google Contacts with mutt

### ISSUE THREAD

**Issue by bamos** [bamos/dotfiles#17]
+ https://hynek.me/articles/my-mutt-gmail-setup/
+ http://stevelosh.com/blog/2012/10/the-homely-mutt/

Hi @zmughal - Do you use mutt between multiple computers?
I'd like an easy solution to synchronize mutt/contacts from a few computers.
Merging the file by hand isn't difficult, though, so automation or switching
to Google Contacts here might not be worth it.

**Comment by bamos** [comment]
Currently leaning towards using
https://github.com/bamos/python-scripts/blob/master/python3/merge-mutt-contacts.py

**Comment by zmughal** [comment]
Yeah, what I do is use [unison](http://www.cis.upenn.edu/~bcpierce/unison/). My folder structure is 

```
~/.mutt
  + rc
    - muttrc.account0
    - muttrc.account1
    - muttrc.account2
    + private/                 # private directory
      - muttrc.account0
      - muttrc.account1
      - muttrc.account2
      + addressbook/
        - gmail-contacts.vcf
```

I only put the parts above `private/` directory in a public repository. I currently haven't automated the whole contacts adding process. What I do is grab the VCard file from Gmail and use [lbdb](https://www.spinnaker.de/lbdb/) to read in addresses.

Then unison syncs up all my dotfiles for me.

It's not clean, but it works. There are only a couple addresses I need often, so I put those in as mutt aliases. :-P

**Comment by zmughal** [comment]
Oh and if you're using Gmail and have lots of labels, you might want to try my [IMAP proxy](https://github.com/zmughal/gmail-imap-label) that grabs the Gmail labels and puts them in the `X-Label` header. It's in Debian/Ubuntu as `libnet-gmail-imap-label-perl`.

**Comment by bamos** [comment]
Great information, thanks @zmughal.

**Comment by bamos** [comment]
@zmughal - unison is amazing! Thanks. I should have started using it earlier. :-)
